name: CI/CD - Deploy to Railway

on:
  push:
    branches:
      - staging

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    needs: [ci]
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: 0c59153b-edea-4c57-b226-826001b344d9
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_STAGING_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Staging
        run: railway up --service=${{ env.SVC_ID }}
