name: CI + Deploy Production

on:
  push:
    branches:
      - main

jobs:
  ci-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        working-directory: backend
        run: uv sync --frozen

      - name: Lint
        working-directory: backend
        run: uvx ruff check .

      - name: Docker build
        working-directory: backend
        run: docker build -t api-ci .
    
  ci-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: frontend
        run: npm install

      - name: Lint
        working-directory: frontend
        run: npm run lint --if-present

      - name: Build docker image
        working-directory: frontend
        run: docker build -t frontend-ci .

  deploy-backend:
    runs-on: ubuntu-latest
    needs: ci-backend
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: 0c59153b-edea-4c57-b226-826001b344d9
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_MAIN_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Production
        working-directory: backend
        run: railway up --service=${{ env.SVC_ID }} --ci
  
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: ci-frontend
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: 17bdbc24-c8f2-495e-afb9-3ebd0967388e
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_MAIN_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Production
        working-directory: backend
        run: railway up --service=${{ env.SVC_ID }} --ci
