name: CI + Deploy Production

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        working-directory: backend
        run: uv sync --frozen

      - name: Lint
        working-directory: backend
        run: uvx ruff check .

      - name: Docker build
        working-directory: backend
        run: docker build -t api-ci .

  deploy-backend:
    runs-on: ubuntu-latest
    needs: ci
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: 0c59153b-edea-4c57-b226-826001b344d9
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_MAIN_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Production
        working-directory: backend
        run: railway up --service=${{ env.SVC_ID }} --ci
  
  #TODO: deploy-frontend
